# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 17:44
from __future__ import unicode_literals
from django.db import migrations, models
from stats.models import BattingAvg


def add_data(apps, schema_editor):
    BattingAvg.objects.create(name='Manny Machado', position='CF')
    BattingAvg.objects.create(name='Chris Davis', position='C')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattingAvg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('games', models.FloatField()),
                ('at_bats', models.FloatField()),
                ('runs', models.FloatField()),
                ('hits', models.FloatField()),
                ('doubles', models.FloatField()),
                ('triples', models.FloatField()),
                ('home_runs', models.FloatField()),
                ('rbi', models.FloatField()),
                ('strike_outs', models.FloatField()),
                ('average', models.FloatField()),
            ],
        ),  migrations.RunPython(add_data)
    ]
