# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 18:29
from __future__ import unicode_literals
from django.db import migrations
from stats.models import BattingAvg


def add_data(apps, schema_editor):
    BattingAvg.objects.create(name='Kim, H', position='LF', games=19, at_bats=55, runs=8, hits=21, doubles=4, triples=0,
                              home_runs=1, rbi=3, strike_outs=8, average=0.382)
    BattingAvg.objects.create(name='Machado, M', position='3B', games=51, at_bats=207, runs=38, hits=65, doubles=21,
                              triples=0, home_runs=13, rbi=31, strike_outs=40, average=0.314)
    BattingAvg.objects.create(name='Reimold, N', position='LF', games=34, at_bats=80, runs=13, hits=24, doubles=4,
                              triples=1, home_runs=4, rbi=10, strike_outs=22, average=0.3)
    BattingAvg.objects.create(name='Trumbo, M', position='RF', games=51, at_bats=201, runs=29, hits=57, doubles=8,
                              triples=1, home_runs=15, rbi=39, strike_outs=59, average=0.284)
    BattingAvg.objects.create(name='Wieters, M', position='C', games=35, at_bats=128, runs=11, hits=36, doubles=7,
                              triples=0, home_runs=4, rbi=20, strike_outs=35, average=0.281)
    BattingAvg.objects.create(name='Schoop, J'	, position='2B', games=51, at_bats=187, runs=20, hits=50, doubles=10,
                              triples=1, home_runs=8, rbi=30, strike_outs=44, average=0.267)
    BattingAvg.objects.create(name='Rickard, J', position='LF', games=50, at_bats=177, runs=23, hits=44, doubles=7,
                              triples=0, home_runs=4, rbi=11, strike_outs=40, average=0.249)
    BattingAvg.objects.create(name='Hardy, J', position='SS', games=22, at_bats=78, runs=11, hits=19, doubles=7,
                              triples=0, home_runs=2, rbi=8, strike_outs=13, average=0.244)
    BattingAvg.objects.create(name='Jones, A', position='CF', games=47, at_bats=181, runs=23, hits=43, doubles=8,
                              triples=0, home_runs=5, rbi=23, strike_outs=38, average=0.238)
    BattingAvg.objects.create(name='Davis, C', position='1B', games=51, at_bats=186, runs=37, hits=41, doubles=10,
                              triples=0, home_runs=10, rbi=28, strike_outs=70, average=0.22)
    BattingAvg.objects.create(name='Alvarez, P', position='DH', games=36, at_bats=108, runs=7, hits=23, doubles=8,
                              triples=0, home_runs=3, rbi=12, strike_outs=28, average=0.213)
    BattingAvg.objects.create(name='Flaherty, R', position='3B', games=28, at_bats=67, runs=5, hits=13, doubles=2,
                              triples=0, home_runs=0, rbi=4, strike_outs=22, average=0.194)
    BattingAvg.objects.create(name='Joseph, C', position='C', games=23, at_bats=66, runs=5, hits=12, doubles=2,
                              triples=0, home_runs=0, rbi=0, strike_outs=14, average=0.182)
    BattingAvg.objects.create(name='Janish, P', position='SS', games=7, at_bats=17, runs=1, hits=2, doubles=1,
                              triples=0, home_runs=0, rbi=0, strike_outs=2, average=0.118)


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20160606_1823'),
    ]

    operations = [
        migrations.RunPython(add_data)
    ]
